export const siteName = "SatiricTech";
export const siteUrl =
	process.env.NEXT_PUBLIC_SITE_URL ||
	(process.env.NODE_ENV === "production"
		? "https://www.satiric-tech.info"
		: "http://localhost:3000");
export const siteKeywords = [
	"news",
	"tech",
	"technology",
	"satire",
	"tech satire",
	"news tech news",
	"tech news tech",
	"tech and news",
	"tech newspapers",
	"newsletter on technology",
	"newsletter on tech",
	"tech news satire",
	"technology humor",
	"tech news parody",
	"satirical tech news",
	"AI-generated satire",
	"tech industry commentary",
	"funny tech news",
	"tech news",
	"tech journalism satire",
	"satiricTech",
	"satiric",
	"satiric-tech",
	"satirical-tech",
	"tech satire",
	"satire tech",
	"news today",
	"tech news today",
	"latest tech news",
	"latest news",
	"latest in tech",
	"latest in technology",
	"latest technology",
	"latest tech",
	"us news",
	"us tech news",
	"latest news today",
	"best tech news",
	"best news",
	"technology newsletter",
	"tech newsletter",
	siteName,
];
